### ISSUE TITLE
Can't use Introspect on macCatalyst Projects

### ISSUE THREAD

**Issue by Ash-Bash** [siteline/SwiftUI-Introspect#33] opened 2020-06-19 00:19 UTC
Can't use Introspect on macCatalyst Projects, it thinks im running a full blown AppKit Project instead of UIKit running on Mac.

**Comment by orospakr** [comment] 2020-06-19 01:46
Hey @Ash-Bash this is a known issue, a regression in the most recent release, and a fix is in master (I think), but a release hasn't been done. Either go to the penultimate release 0.0.6, or try master.

**Comment by PedroCavaleiro** [comment] 2020-07-02 22:14
Using master works just fine on my project @Ash-Bash

**Comment by JannThomas** [comment] 2021-03-18 17:07
I will close this issue since it works in the newest release.

**Closed by JannThomas** 2021-03-18 17:07 UTC
