### ISSUE TITLE
Does not work with Mac Catalyst

### ISSUE THREAD

**Issue by Kamik423** [siteline/SwiftUI-Introspect#13] opened 2020-02-17 10:57 UTC
When using in with Mac Catalyst / UIKit for Mac were are compiler errors, due to

https://github.com/siteline/SwiftUI-Introspect/blob/de5c32c15ae169cfcb27397ffb2734dcd0e1e6d5/Introspect/ViewExtensions.swift#L117

since some AppKit functionality is supported, but it ist still based on UIKit.

Many subsequent lines throw error then, like

```
'NSView' is unavailable in Mac Catalyst
```

in 

https://github.com/siteline/SwiftUI-Introspect/blob/de5c32c15ae169cfcb27397ffb2734dcd0e1e6d5/Introspect/ViewExtensions.swift#L121

```
'NSTableView' is unavailable in Mac Catalyst
```
in

https://github.com/siteline/SwiftUI-Introspect/blob/de5c32c15ae169cfcb27397ffb2734dcd0e1e6d5/Introspect/ViewExtensions.swift#L132

and so on.

**Comment by orospakr** [comment] 2020-02-21 22:05
Pretty sure this is a regression; it works with 0.0.6.

**Comment by ldiqual** [comment] 2020-02-24 23:52
Pretty sure this is due to https://github.com/siteline/SwiftUI-Introspect/commit/5d78ad7d17ecbb32056dd22a0f6c0becdd06ff67 where we added macOS support. `AppKit` gets imported, but we need to annotate `NSView` methods to indicate that they're unavailable on catalyst. Will do that this week – happy to review a PR if you'd like this faster. Thanks for your patience!

**Comment by samdeane** [comment] 2020-03-03 14:14
See PR #15.

**Comment by ldiqual** [comment] 2020-03-04 23:29
Thanks for reporting! Thanks to @samdeane we'll have this fixed after https://github.com/siteline/SwiftUI-Introspect/pull/17 gets merged. Thanks for your patience

**Comment by ldiqual** [comment] 2020-03-28 23:00
This is available in `master`, closing now

**Closed by ldiqual** 2020-03-28 23:00 UTC
