### ISSUE TITLE
Bottom bar showing on every screen in SwiftUI in iOS 15

### ISSUE THREAD

**Issue by GovindAgarwa** [siteline/SwiftUI-Introspect#137] opened 2021-11-12 17:56 UTC
Hi  
Bottom bar showing every screen So I want to hide this bar when user will click on card(refer screenshots).

To Solve this issue 
 
I am using **Introspect** with the code  **.introspectNavigationController { nav in nav.hidesBottomBarWhenPushed = true }** but its not working in SwiftUI iOS 15.

Please let me know proper solution to hide Bottom bar. Thanks in advance

![simulator_screenshot_3A881CD2-4A77-4202-8F47-DF3D4AD21C8E](https://user-images.githubusercontent.com/24714133/141513672-bfded0b3-1183-40b6-99ad-5c80e5241f62.png)

**Comment by Patrik-svobodik** [comment] 2021-12-31 18:48
I think this is due to the order of operations, you can only introspect it after it has been initialized and being pushed on the screen

Furthermore, you're trying to introspect the navigation controller, that's incorrect, try introspecting the child view controller

**Comment by davdroman** [comment] 2023-06-28 17:51
A bit late to this, but @PatrikTheDev is right on the money, and there's really nothing this library alone can do to circumvent this. So unfortunately I'm closing this for now.

**Closed by davdroman** 2023-06-28 17:51 UTC

**Comment by honkmaster** [comment] 2023-07-01 10:20
FYI: `introspectNavigationController` never worked for us reliably too when we want to hide the bottom bar on **specific** views. What seemed to be quite reliable however, was to use `introspectViewController` and add an additional guard to compare the topViewController. 

´´´
introspectViewController {
  guard $0.navigationController?.topViewController == $0 else { return }
  $0.navigationController?.hidesBottomBarWhenPushed = shouldHide
}
´´´

**Comment by davdroman** [comment] 2023-07-01 10:28
Hmm interesting. Can you provide a minimum reproducible example of this? I'm trying to replicate it but it's still not working for me. I'd really appreciate it. Here's my attempt so far:

```swift
import SwiftUI
import Introspect

struct ContentView: View {
    var body: some View {
        TabView {
            NavigationStack {
                NavigationLink("Tap Me") {
                    Text("Detail View")
                        .introspectViewController {
                            guard $0.navigationController?.topViewController == $0 else { return }
                            $0.navigationController?.hidesBottomBarWhenPushed = true
                        }
                }
                .navigationTitle("Primary View")
            }
            .tabItem {
                Label("Home", systemImage: "house")
            }
        }
    }
}
```

**Comment by davdroman** [comment] 2023-07-05 19:16
Digging even deeper into this, sadly I think this is virtually impossible unless Apple makes some changes to UIKit itself.

I believe there's some internal logic in UIKit which checks if the currently selected tab's root view controller type is `UINavigationController` to determine whether the tab bar should be hidden during a push transition, and if it's not, any `hidesBottomBarWhenPushed` gets ignored completely.

The way `TabView` (UITabBarController) in SwiftUI sets up its `viewControllers` is by first wrapping them in a `UIHostingController`, so there will never be a  `UINavigationController` at the root of a tab, hence `hidesBottomBarWhenPushed` is always ignored.

You can verify this by running the following demo I put together: https://github.com/davdroman/SwiftUIHidesBottomBarWhenPushedExperiment
