### ISSUE TITLE
State modification warning when introspecting

### ISSUE THREAD

**Issue by Skittyblock** [siteline/SwiftUI-Introspect#212] opened 2023-03-29 00:02 UTC
In the below example, I get the runtime warning `[SwiftUI] Modifying state during view update, this will cause undefined behavior.` on the `hit = true` assignment when opening `ChildView`. The second time that `introspectNavigationController` is called, it passes the guard statement because the first time that `hit` is assigned doesn't seem to persist.

I'm not sure if this is a Swift bug or a Introspect bug, but it seems pretty convoluted to me. This is also different behavior from #199.

```swift
struct Anything {}

struct ParentView: View {
    var body: some View {
        NavigationView {
            NavigationLink(destination: ChildView()) {
                Text("Test")
            }
        }
    }
}

struct ChildView: View {
    @State var testString: String = ""

    @State var hit = false
    let bug = [Anything()] // can be anything init'd, e.g. UIView(), but not a literal string or number

    var body: some View {
        Text(testString)
            .introspectNavigationController { _ in
                guard !hit else { return }
                hit = true // still gets through during the second call
            }
            .onAppear {
                testString = "testing" // needs to be something that refreshes the view
            }
    }
}
```

**Comment by lhunath** [comment] 2023-05-16 19:52
SwiftUI doesn't want you modifying the state of a view while the view is being rendered.

The problem here is that from the SwiftUI-Introspect API, it is unclear that the developer should expect the `.introspect` block to behave as render-time.

Two arguments could exist:
1. The introspect block should be considered self-contained: please don't do anything in this block except for modifying the UIKit object you are getting from it.
2. The introspect block is an opportunity for the developer to update his SwiftUI state based on UIKit state.

If [1] is accurate, this is not a bug, but perhaps we can clarify this limitation somehow to the developer.

If [2] is accurate, probably the block should be invoked in a safe context, not during view updates.

**Comment by goors** [comment] 2023-06-13 21:08
I resolved this with:

```
 DispatchQueue.main.async {
                                    
     textEditor.becomeFirstResponder()
}
``` @Skittyblock

**Comment by davdroman** [comment] 2023-06-13 22:20
A combination of @lhunath's and @goors' responses are the answer to this.

I'd add that in general, mutating state while introspecting doesn't really make sense, as you don't really have control of when in the view's lifecycle it takes place. Instead, it's generally standard practice to use `onAppear` for that, or as a last resort go with @goors' workaround of delaying mutation until the next run loop.

I'll be closing this for now, feel free to reopen if needed.

**Closed by davdroman** 2023-06-13 22:20 UTC

**Comment by Skittyblock** [comment] 2023-06-15 03:08
I believe I ran into this when I was trying to introspect the navigation controller in order to store it (since I needed to use it in `onAppear`, as the changes I made kept getting reset by SwiftUI when the view disappeared). It worked fine until I added the "bug" variable in the example, which is what stumped me. The whole thing was essentially a hack-y workaround for fixing a SwiftUI bug though.

I ended up changing my approach slightly in order to prevent the warning from happening; I'm not entirely sure what I was doing before to cause it, but I think I might've been instantiating a `UIBarButtonItem` in an array in the "bug" variable.

**Comment by malhal** [comment] 2024-11-01 18:31
I ran into this problem with the latest version and was surprised to see the issue closed for what seems such a common use case:
```
Table{
...
}
 .introspect(.table, on: .iOS(.v18)) { table in
     self.height = table.contentSize.height
 }
.frame(height: height)

Warning: Modifying state during view update, this will cause undefined behavior.
```
