### ISSUE TITLE
Navigation animation is glitchy when using Introspect to make a text field first responder

### ISSUE THREAD

**Issue by james-rantmedia** [siteline/SwiftUI-Introspect#102] opened 2021-04-06 14:31 UTC
I'm using Introspect to make a text field become first responder programatically (since I haven't found any other way to do this in SwiftUI yet).

The issue that the navigation animation is glitchy when making a text field first responder. This only happens with a navigation animation, ie. using a `NavigationView` and a `NavigationLink` with it's default right-to-left slide animation. It doesn't happen if I do it after presenting a sheet (ie. a modal presentation where the sheet is presented over the previous view, bottom-to-top animation.

I've included a video showing the glitch (and showing it working fine with sheet presentation). Also attached a sample project with the code that reproduces the issue. [introspecttest.zip](https://github.com/siteline/SwiftUI-Introspect/files/6265369/introspecttest.zip)

https://user-images.githubusercontent.com/18418154/113727498-147bb800-96ed-11eb-8ace-995d6e5293f7.mov

**Comment by JannThomas** [comment] 2021-04-24 10:16
Hi @james-rantmedia,

I took a look at your issue and couldn't find a quickly implementable solution using standard components to it. We usually try to offer one, but this seems to be a pretty hard issue.

The problem here is that the introspect functions return the views as fast as they can, basically on render. That is expected behavior. What you want to do here is call the `becomeFirstResponder` function after the view already appeared. With SwiftUI, this is not possible, since `onAppear` executes just before the view enters the viewport, it is comparable to `viewWillAppear` from `UIKit`.

What I could do was add [SchafKit](https://github.com/Quintschaf/SchafKit)'s `viewDidAppear` function. Using that function and saving the text field in the view, I was able to fix the glitchiness. You can take a look at it here: 
[introspecttest.zip](https://github.com/siteline/SwiftUI-Introspect/files/6369373/introspecttest.zip)

That said, this is definitely not an Introspect issue and I will close this issue.

**Closed by JannThomas** 2021-04-24 10:16 UTC

**Comment by james-rantmedia** [comment] 2021-04-26 08:10
Thanks for the info, I'll look into it!
